version: "3.8"
services:
    user-app:
        container_name: ltelle-eatery-user
        image: hoangkhoanguyen/ltelle-eatery-user
        build:
            context: .
        ports:
            - "4040:3000"
        networks:
            - proxy-net

networks:
    proxy-net:
        name: proxy-net
        driver: bridge
