name: Deploy Development

on:
    push:
        branches: ["deploy/dev/*"]
    pull_request:
        branches: ["deploy/dev/*"]

jobs:
    build-dev:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Extract App Name from Branch
              id: extract
              run: |
                  BRANCH_NAME=${GITHUB_REF##*/}
                  echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
                  APP_NAME=${BRANCH_NAME##*/}
                  echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: build and push
              uses: docker/build-push-action@v5
              with:
                  context: ./${{ steps.extract.outputs.app_name }}
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}-${{ steps.extract.outputs.app_name }}:dev
                  file: ./${{ steps.extract.outputs.app_name }}/Dockerfile

            - name: Deploy to VPS via SSH
              uses: appleboy/ssh-action@v1
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      cd ../home/apps
                      docker compose pull ${{ steps.extract.outputs.app_name }}
                      docker compose up ${{ steps.extract.outputs.app_name }} -d --force-recreate
